repos:
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.4"
    hooks:
      - id: prettier
        types: [file]
        files: \.(js|jsx|ts|tsx|yaml|yml|json|json5)$
        additional_dependencies:
          - prettier
          - "@whtsky/prettier-config"
